url=https://www.udemy.com
cartUrl=https://www.udemy.com/cart/
myLearningURL=https://www.udemy.com/home/my-courses/
invalidCartUrl=https://www.udemy.com/cart/random123hdgfd
name=Bhavadharani
email=dharanivedha06@gmail.com
browser=chrome